---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.port }}
    nodePort: {{ .Values.service.nodeport }}
    targetPort: postgresql
  selector:
    app: {{ template "postgresql.name" . }}
    release: {{ .Release.Name | quote }}
