apiVersion: v1
kind: Service
metadata:
  name: {{ include "yavor.fullname" . }}
  labels:
    {{- include "yavor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodeport }}
      name: http
  selector:
    {{- include "yavor.selectorLabels" . | nindent 4 }}
